export const products = [
  {
    id: 1,
    name: "Premium Headphones",
    price: 199,
    category: "audio",
    image: "/premium-headphones.png",
    description: "High-quality sound with active noise cancellation. Perfect for music lovers and professionals.",
    stock: 25,
  },
  {
    id: 2,
    name: "Wireless Speaker",
    price: 149,
    category: "audio",
    image: "/wireless-speaker.jpg",
    description: "360-degree sound with waterproof design. Great for outdoor and indoor use.",
    stock: 15,
  },
  {
    id: 3,
    name: "Smart Watch",
    price: 299,
    category: "wearables",
    image: "/smartwatch-lifestyle.png",
    description: "Track your fitness and stay connected. Heart rate monitor and GPS included.",
    stock: 30,
  },
  {
    id: 4,
    name: "Professional Camera",
    price: 899,
    category: "photography",
    image: "/professional-camera.png",
    description: "4K video recording with advanced autofocus. Perfect for content creators.",
    stock: 8,
  },
  {
    id: 5,
    name: "Portable Charger",
    price: 49,
    category: "accessories",
    image: "/portable-power-bank-charger.jpg",
    description: "20000mAh capacity. Charge multiple devices simultaneously.",
    stock: 50,
  },
  {
    id: 6,
    name: "USB-C Cable",
    price: 19,
    category: "accessories",
    image: "/usb-c-cable.jpg",
    description: "Fast charging and data transfer. Durable and tangle-free design.",
    stock: 100,
  },
]
